// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UpSkillingPlatform.Infrastructure.Data;

#nullable disable

namespace UpSkillingPlatform.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251115183647_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("UpSkillingPlatform.Domain.Entities.Competencia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Categoria")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("categoria");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.ToTable("competencias", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Categoria = "Tecnologia",
                            Descricao = "Machine Learning, Deep Learning, NLP",
                            Nome = "Inteligência Artificial"
                        },
                        new
                        {
                            Id = 2L,
                            Categoria = "Tecnologia",
                            Descricao = "Data Science, Business Intelligence, Big Data",
                            Nome = "Análise de Dados"
                        },
                        new
                        {
                            Id = 3L,
                            Categoria = "Tecnologia",
                            Descricao = "AWS, Azure, Google Cloud",
                            Nome = "Cloud Computing"
                        },
                        new
                        {
                            Id = 4L,
                            Categoria = "Tecnologia",
                            Descricao = "Frontend e Backend moderno",
                            Nome = "Desenvolvimento Web"
                        },
                        new
                        {
                            Id = 5L,
                            Categoria = "Humana",
                            Descricao = "Comunicação clara e assertiva",
                            Nome = "Comunicação Efetiva"
                        },
                        new
                        {
                            Id = 6L,
                            Categoria = "Humana",
                            Descricao = "Colaboração e cooperação",
                            Nome = "Trabalho em Equipe"
                        },
                        new
                        {
                            Id = 7L,
                            Categoria = "Humana",
                            Descricao = "Análise e resolução de problemas",
                            Nome = "Pensamento Crítico"
                        },
                        new
                        {
                            Id = 8L,
                            Categoria = "Gestão",
                            Descricao = "Metodologias ágeis e tradicionais",
                            Nome = "Gestão de Projetos"
                        });
                });

            modelBuilder.Entity("UpSkillingPlatform.Domain.Entities.Matricula", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataInscricao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_inscricao");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<long>("TrilhaId")
                        .HasColumnType("bigint")
                        .HasColumnName("trilha_id");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("TrilhaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("matriculas", (string)null);
                });

            modelBuilder.Entity("UpSkillingPlatform.Domain.Entities.Trilha", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("CargaHoraria")
                        .HasColumnType("int")
                        .HasColumnName("carga_horaria");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT")
                        .HasColumnName("descricao");

                    b.Property<string>("FocoPrincipal")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("foco_principal");

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nivel");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.ToTable("trilhas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CargaHoraria = 40,
                            Descricao = "Aprenda os conceitos fundamentais de IA e como aplicar algoritmos de ML",
                            FocoPrincipal = "IA",
                            Nivel = "INICIANTE",
                            Nome = "Fundamentos de IA e Machine Learning"
                        },
                        new
                        {
                            Id = 2L,
                            CargaHoraria = 120,
                            Descricao = "Torne-se um cientista de dados completo com Python e ferramentas modernas",
                            FocoPrincipal = "Dados",
                            Nivel = "INTERMEDIARIO",
                            Nome = "Cientista de Dados Profissional"
                        },
                        new
                        {
                            Id = 3L,
                            CargaHoraria = 80,
                            Descricao = "Domine arquiteturas cloud escaláveis e resilientes",
                            FocoPrincipal = "Cloud",
                            Nivel = "AVANCADO",
                            Nome = "Arquitetura Cloud Avançada"
                        },
                        new
                        {
                            Id = 4L,
                            CargaHoraria = 30,
                            Descricao = "Desenvolva habilidades humanas essenciais para liderança e colaboração",
                            FocoPrincipal = "Soft Skills",
                            Nivel = "INICIANTE",
                            Nome = "Soft Skills para o Futuro"
                        });
                });

            modelBuilder.Entity("UpSkillingPlatform.Domain.Entities.TrilhaCompetencia", b =>
                {
                    b.Property<long>("TrilhaId")
                        .HasColumnType("bigint")
                        .HasColumnName("trilha_id");

                    b.Property<long>("CompetenciaId")
                        .HasColumnType("bigint")
                        .HasColumnName("competencia_id");

                    b.HasKey("TrilhaId", "CompetenciaId");

                    b.HasIndex("CompetenciaId");

                    b.ToTable("trilha_competencia", (string)null);

                    b.HasData(
                        new
                        {
                            TrilhaId = 1L,
                            CompetenciaId = 1L
                        },
                        new
                        {
                            TrilhaId = 1L,
                            CompetenciaId = 7L
                        },
                        new
                        {
                            TrilhaId = 2L,
                            CompetenciaId = 2L
                        },
                        new
                        {
                            TrilhaId = 2L,
                            CompetenciaId = 1L
                        },
                        new
                        {
                            TrilhaId = 3L,
                            CompetenciaId = 3L
                        },
                        new
                        {
                            TrilhaId = 3L,
                            CompetenciaId = 8L
                        },
                        new
                        {
                            TrilhaId = 4L,
                            CompetenciaId = 5L
                        },
                        new
                        {
                            TrilhaId = 4L,
                            CompetenciaId = 6L
                        },
                        new
                        {
                            TrilhaId = 4L,
                            CompetenciaId = 7L
                        });
                });

            modelBuilder.Entity("UpSkillingPlatform.Domain.Entities.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AreaAtuacao")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("area_atuacao");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_cadastro");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("email");

                    b.Property<string>("NivelCarreira")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nivel_carreira");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("UpSkillingPlatform.Domain.Entities.Matricula", b =>
                {
                    b.HasOne("UpSkillingPlatform.Domain.Entities.Trilha", "Trilha")
                        .WithMany("Matriculas")
                        .HasForeignKey("TrilhaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_matricula_trilha");

                    b.HasOne("UpSkillingPlatform.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Matriculas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_matricula_usuario");

                    b.Navigation("Trilha");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("UpSkillingPlatform.Domain.Entities.TrilhaCompetencia", b =>
                {
                    b.HasOne("UpSkillingPlatform.Domain.Entities.Competencia", "Competencia")
                        .WithMany("TrilhaCompetencias")
                        .HasForeignKey("CompetenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_trilha_competencia_competencia");

                    b.HasOne("UpSkillingPlatform.Domain.Entities.Trilha", "Trilha")
                        .WithMany("TrilhaCompetencias")
                        .HasForeignKey("TrilhaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_trilha_competencia_trilha");

                    b.Navigation("Competencia");

                    b.Navigation("Trilha");
                });

            modelBuilder.Entity("UpSkillingPlatform.Domain.Entities.Competencia", b =>
                {
                    b.Navigation("TrilhaCompetencias");
                });

            modelBuilder.Entity("UpSkillingPlatform.Domain.Entities.Trilha", b =>
                {
                    b.Navigation("Matriculas");

                    b.Navigation("TrilhaCompetencias");
                });

            modelBuilder.Entity("UpSkillingPlatform.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Matriculas");
                });
#pragma warning restore 612, 618
        }
    }
}
